import { StyleSheet, View, type ColorValue } from 'react-native';

/**
 * Bar height proportions – creates a fun, bouncy waveform shape.
 * These match the SVG logo generated by scripts/generate-assets.js.
 */
const BAR_HEIGHTS = [0.30, 0.55, 0.80, 0.50, 1.00, 0.45, 0.90, 0.60, 0.35];

/** Gap as a fraction of bar width. */
const GAP_RATIO = 0.35;

const BAR_COUNT = BAR_HEIGHTS.length;

type Props = {
  /** Overall size (dp) – the tallest bar will be this height. */
  size?: number;
  /** Bar colour. Accepts any RN `ColorValue` so the tab-icon callback's
   *  `OpaqueColorValue` (SDK 56 / RN 0.85 typing tightening) flows in. */
  color?: ColorValue;
};

export default function WaveformLogo({ size = 130, color = '#FFFFFF' }: Props) {
  const barWidth = size / (BAR_COUNT + (BAR_COUNT - 1) * GAP_RATIO);
  const gap = barWidth * GAP_RATIO;
  const pillRadius = barWidth / 2;

  return (
    <View style={styles.wrap}>
      {BAR_HEIGHTS.map((h, i) => (
        <View
          key={i}
          style={{
            width: barWidth,
            height: size * h,
            borderRadius: pillRadius,
            backgroundColor: color,
            marginLeft: i === 0 ? 0 : gap,
          }}
        />
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
